version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "06:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 25
  ignore:
  - dependency-name: org.flamingo-mc:flamingo-mc
    versions:
    - ">= 5.9.x"
