language: java

sudo: false

install:
  # install without testing
  - mvn install -Dmaven.test.skip=true -B -V -fae -q

script:
  # execute unit and integration tests
  - mvn -e test verify -B

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

os:
  - linux

matrix:
  fast_finish: true

cache:
  directories:
  - $HOME/.m2
