dist: trusty
sudo: false
language: java

addons:
  postgresql: "9.4"

before_install:
  # installeer een up-2-date Maven versie
  - wget https://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
  - unzip -qq apache-maven-3.3.9-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
  - psql --version
  - psql -U postgres -c 'CREATE ROLE ibis LOGIN NOSUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;'
  - psql -U postgres -c 'CREATE ROLE geo LOGIN NOSUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;'
  - psql -U postgres -c 'CREATE ROLE geolees LOGIN NOSUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;'
  - psql -U postgres -c 'CREATE ROLE geoedit LOGIN NOSUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;'
  - psql -U postgres -c 'create database ibis WITH OWNER = ibis'
  - psql -U postgres -c 'create schema "IBIS" AUTHORIZATION ibis';
  - psql -U postgres -c 'ALTER DATABASE "ibis" SET search_path = "IBIS", public;'
  - psql -U postgres -d ibis -c 'create extension postgis;'
  - ls -l ./src/main/ddl/
  - psql -U postgres -w -d ibis -a -f ./src/main/ddl/create_ibis_database.sql

install:
  # install without testing
  - mvn install -Dmaven.test.skip=true -B -V -fae -q -pl '!dist'

before_script:

script:
  # execute unit and integration tests
  - mvn -e test integration-test -B -pl '!dist'
  - if [ "$TRAVIS_JDK_VERSION" == oraclejdk8 ]; then
         mvn javadoc:javadoc;
    fi
  - if [ "$TRAVIS_JDK_VERSION" == oraclejdk8 ]; then
         mvn javadoc:test-javadoc;
    fi

after_success:

after_failure:

after_script:

jdk:
  - oraclejdk8
  - openjdk8

os:
  - linux

matrix:
  fast_finish: true

cache:
  directories:
  - $HOME/.m2
