language: java

addons:
  postgresql: 10
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - graphviz

before_install:
  - mvn -v
  - export PAGER=cat
  - psql --version
  - psql -U postgres -c 'CREATE ROLE ibis LOGIN NOSUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;'
  - psql -U postgres -c 'CREATE ROLE geo LOGIN NOSUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;'
  - psql -U postgres -c 'CREATE ROLE geolees LOGIN NOSUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;'
  - psql -U postgres -c 'CREATE ROLE geoedit LOGIN NOSUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;'
  - psql -U postgres -c 'create database ibis WITH OWNER = ibis'
  - psql -U postgres -c 'create schema "IBIS" AUTHORIZATION ibis';
  - psql -U postgres -c 'ALTER DATABASE "ibis" SET search_path = "IBIS", public;'
  - psql -U postgres -d ibis -c 'SELECT version();'
  - psql -U postgres -d ibis -c 'create extension postgis;'
  - psql -U postgres -d ibis -c 'SELECT PostGIS_full_version();'
  - ls -l ./src/main/ddl/
  - psql -U postgres -w -d ibis -a -f ./src/main/ddl/create_ibis_database.sql
  - psql -U postgres -w -d ibis -a -f ./src/main/ddl/upgrade3.1-4.0-views.sql
  - psql -U postgres -w -d ibis -a -f ./src/main/ddl/upgrade4.0-4.1-views.sql

install:
  # install without any testing
  - mvn install -Dmaven.test.skip=true -B -V -fae -q -pl '!dist'

before_script:

script:
  # execute unit and integration tests
  - mvn -e test integration-test -B -pl '!dist'
  # check javadoc
  - if [ "$TRAVIS_JDK_VERSION" == openjdk8 ]; then
         mvn javadoc:javadoc;
    fi
  - if [ "$TRAVIS_JDK_VERSION" == openjdk8 ]; then
         mvn javadoc:test-javadoc;
    fi

after_success:

after_failure:

after_script:

jdk:
  - openjdk8

os:
  - linux

matrix:
  fast_finish: true

cache:
  directories:
  - $HOME/.m2
