version: '{build}-({branch})'

skip_tags: true

shallow_clone: false

environment:
  fast_finish: true
  MVN_VERSION: 3.3.9
  matrix:
  - JDK: JDK7
    JAVA_HOME: C:\Program Files\Java\jdk1.7.0
  - JDK: JDK8
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - ps: >-
      Add-Type -AssemblyName System.IO.Compression.FileSystem
          if (!(Test-Path -Path "C:\maven" )) {
            (new-object System.Net.WebClient).DownloadFile(
              "https://www-eu.apache.org/dist/maven/maven-3/$env:MVN_VERSION/binaries/apache-maven-$env:MVN_VERSION-bin.zip",
              'C:\maven-bin.zip'
            )
            [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
          }
  - cmd: SET PATH=C:\maven\apache-maven-%MVN_VERSION%\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: echo %PATH%
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-http-proxy.ps1'))
  - ps: .\set-maven-proxy.ps1
  - mvn install -Dmaven.test.skip=true -B -V -fae -q -pl "!dist"

cache:
  - C:\maven\apache-maven-%MVN_VERSION% -> appveyor.yml
  # don't cache maven repo, AppVeyor has 500MB cache limit - C:\Users\appveyor\.m2\repository -> pom.xml

build: off

test_script:
  - mvn -e test verify -B -pl "!dist"
